# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_intervalmap <- function() {
    .Call(`_superintervals_create_intervalmap`)
}

add_interval <- function(container, start, end, value = NULL) {
    invisible(.Call(`_superintervals_add_interval`, container, start, end, value))
}

build_index <- function(container) {
    invisible(.Call(`_superintervals_build_index`, container))
}

get_interval_at <- function(container, r_index) {
    .Call(`_superintervals_get_interval_at`, container, r_index)
}

get_start_at <- function(container, r_index) {
    .Call(`_superintervals_get_start_at`, container, r_index)
}

get_end_at <- function(container, r_index) {
    .Call(`_superintervals_get_end_at`, container, r_index)
}

get_data_at <- function(container, r_index) {
    .Call(`_superintervals_get_data_at`, container, r_index)
}

clear_intervals <- function(container) {
    invisible(.Call(`_superintervals_clear_intervals`, container))
}

reserve_intervals <- function(container, n) {
    invisible(.Call(`_superintervals_reserve_intervals`, container, n))
}

get_size <- function(container) {
    .Call(`_superintervals_get_size`, container)
}

cpp_has_overlaps <- function(container, start, end) {
    .Call(`_superintervals_cpp_has_overlaps`, container, start, end)
}

count_overlaps <- function(container, start, end) {
    .Call(`_superintervals_count_overlaps`, container, start, end)
}

cpp_search_values <- function(container, start, end) {
    .Call(`_superintervals_cpp_search_values`, container, start, end)
}

search_indexes <- function(container, start, end) {
    .Call(`_superintervals_search_indexes`, container, start, end)
}

cpp_search_keys <- function(container, start, end) {
    .Call(`_superintervals_cpp_search_keys`, container, start, end)
}

cpp_search_items <- function(container, start, end) {
    .Call(`_superintervals_cpp_search_items`, container, start, end)
}

get_coverage <- function(container, start, end) {
    .Call(`_superintervals_get_coverage`, container, start, end)
}

