# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

create_intervalmap <- function() {
    .Call(`_superintervalsr_create_intervalmap`)
}

create_intervalmap_from_vectors <- function(starts, ends, values) {
    .Call(`_superintervalsr_create_intervalmap_from_vectors`, starts, ends, values)
}

add_interval <- function(container, start, end, value = NULL) {
    invisible(.Call(`_superintervalsr_add_interval`, container, start, end, value))
}

build_index <- function(container) {
    invisible(.Call(`_superintervalsr_build_index`, container))
}

get_interval_at <- function(container, r_index) {
    .Call(`_superintervalsr_get_interval_at`, container, r_index)
}

get_start_at <- function(container, r_index) {
    .Call(`_superintervalsr_get_start_at`, container, r_index)
}

get_end_at <- function(container, r_index) {
    .Call(`_superintervalsr_get_end_at`, container, r_index)
}

get_data_at <- function(container, r_index) {
    .Call(`_superintervalsr_get_data_at`, container, r_index)
}

get_all_starts <- function(container) {
    .Call(`_superintervalsr_get_all_starts`, container)
}

get_all_ends <- function(container) {
    .Call(`_superintervalsr_get_all_ends`, container)
}

get_all_values <- function(container) {
    .Call(`_superintervalsr_get_all_values`, container)
}

clear_intervals <- function(container) {
    invisible(.Call(`_superintervalsr_clear_intervals`, container))
}

reserve_intervals <- function(container, n) {
    invisible(.Call(`_superintervalsr_reserve_intervals`, container, n))
}

get_size <- function(container) {
    .Call(`_superintervalsr_get_size`, container)
}

cpp_has_overlaps <- function(container, start, end) {
    .Call(`_superintervalsr_cpp_has_overlaps`, container, start, end)
}

has_overlaps_batch <- function(container, starts, ends) {
    .Call(`_superintervalsr_has_overlaps_batch`, container, starts, ends)
}

count_overlaps <- function(container, start, end) {
    .Call(`_superintervalsr_count_overlaps`, container, start, end)
}

cpp_search_values <- function(container, start, end) {
    .Call(`_superintervalsr_cpp_search_values`, container, start, end)
}

search_indexes <- function(container, start, end) {
    .Call(`_superintervalsr_search_indexes`, container, start, end)
}

cpp_search_keys <- function(container, start, end) {
    .Call(`_superintervalsr_cpp_search_keys`, container, start, end)
}

cpp_search_items <- function(container, start, end) {
    .Call(`_superintervalsr_cpp_search_items`, container, start, end)
}

get_coverage <- function(container, start, end) {
    .Call(`_superintervalsr_get_coverage`, container, start, end)
}

search_idxs_batch <- function(container, starts, ends) {
    .Call(`_superintervalsr_search_idxs_batch`, container, starts, ends)
}

count_batch <- function(container, starts, ends) {
    .Call(`_superintervalsr_count_batch`, container, starts, ends)
}

search_values_batch <- function(container, starts, ends) {
    .Call(`_superintervalsr_search_values_batch`, container, starts, ends)
}

cpp_search_point <- function(container, point) {
    .Call(`_superintervalsr_cpp_search_point`, container, point)
}

cpp_merge_overlaps <- function(container) {
    .Call(`_superintervalsr_cpp_merge_overlaps`, container)
}

cpp_union_with <- function(container_a, container_b) {
    .Call(`_superintervalsr_cpp_union_with`, container_a, container_b)
}

cpp_intersection <- function(container_a, container_b) {
    .Call(`_superintervalsr_cpp_intersection`, container_a, container_b)
}

cpp_difference <- function(container_a, container_b) {
    .Call(`_superintervalsr_cpp_difference`, container_a, container_b)
}

cpp_symmetric_difference <- function(container_a, container_b) {
    .Call(`_superintervalsr_cpp_symmetric_difference`, container_a, container_b)
}

cpp_gaps <- function(container, lo, hi, fill = NULL) {
    .Call(`_superintervalsr_cpp_gaps`, container, lo, hi, fill)
}

cpp_span <- function(container) {
    .Call(`_superintervalsr_cpp_span`, container)
}

cpp_expand <- function(container, left, right, lo, hi) {
    .Call(`_superintervalsr_cpp_expand`, container, left, right, lo, hi)
}

cpp_flank <- function(container, left, right, lo, hi) {
    .Call(`_superintervalsr_cpp_flank`, container, left, right, lo, hi)
}

cpp_unique_intervals <- function(container) {
    .Call(`_superintervalsr_cpp_unique_intervals`, container)
}

